name: Run tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-laravel-8:
    name: PHP ${{ matrix.php }} / Laravel 8.x
    runs-on: ubuntu-latest
    strategy:
      matrix:
#        php: [7.4, 8.0, 8.1, 8.2, 8.3]
        php: [7.4]
    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP ${{ matrix.php }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, bcmath, xml, ctype, json, pdo_sqlite

      - name: Require Laravel & Testbench
        run: |
          composer require --dev laravel/framework:8.x --no-update
          composer require --dev orchestra/testbench:^6.0 --no-update
          composer update --prefer-dist --no-interaction --no-scripts

      - name: Ensure bootstrap/cache is writable
        run: |
          mkdir -p vendor/orchestra/workbench/bootstrap/cache

      - name: Publish Config
        run: ./vendor/bin/testbench  vendor:publish --provider="BinaryBuilds\LaritorClient\LaritorServiceProvider" --force

      - name: Run Tests
        run: ./vendor/bin/phpunit

#  test-laravel-9:
#    name: PHP ${{ matrix.php }} / Laravel 9.x
#    runs-on: ubuntu-latest
#    strategy:
#      matrix:
#        php: [8.0]
#    steps:
#      - uses: actions/checkout@v4
#
#      - name: Setup PHP ${{ matrix.php }}
#        uses: shivammathur/setup-php@v2
#        with:
#          php-version: ${{ matrix.php }}
#          extensions: mbstring, bcmath, xml, ctype, json, pdo_sqlite
#
#      - name: Require Laravel & Testbench
#        run: |
#          composer require laravel/framework:9.x --no-update
#          composer require --dev orchestra/testbench:^7.0 --no-update
#          composer update --prefer-dist --no-interaction --no-scripts
#
#      - name: Publish Config
#        run: ./vendor/bin/testbench  vendor:publish --provider="BinaryBuilds\LaritorClient\LaritorServiceProvider" --force
#
#      - name: Run Tests
#        run: ./vendor/bin/phpunit


#  test-laravel-10:
#    name: PHP ${{ matrix.php }} / Laravel 10.x
#    runs-on: ubuntu-latest
#    strategy:
#      matrix:
#        php: [8.1, 8.2, 8.3]
#    steps:
#      - uses: actions/checkout@v4
#
#      - name: Setup PHP ${{ matrix.php }}
#        uses: shivammathur/setup-php@v2
#        with:
#          php-version: ${{ matrix.php }}
#          extensions: mbstring, bcmath, xml, ctype, json, pdo_sqlite
#
#      - name: Require Laravel & Testbench
#        run: |
#          composer require --dev laravel/framework:10.x --no-update
#          composer require --dev orchestra/testbench:^8.0 --no-update
#          composer update --prefer-dist --no-interaction --no-scripts
#
#      - name: Publish Config
#        run: ./vendor/bin/testbench  vendor:publish --provider="BinaryBuilds\LaritorClient\LaritorServiceProvider" --force
#
#      - name: Run Tests
#        run: ./vendor/bin/phpunit

#  test-laravel-11:
#    name: PHP ${{ matrix.php }} / Laravel 11.x
#    runs-on: ubuntu-latest
#    strategy:
#      matrix:
#        php: [8.2, 8.3]
#        include:
#          - laravel: 11.x
#            testbench: ^9.0
#    steps:
#      - uses: actions/checkout@v4
#
#      - name: Setup PHP ${{ matrix.php }}
#        uses: shivammathur/setup-php@v2
#        with:
#          php-version: ${{ matrix.php }}
#          extensions: mbstring, bcmath, xml, ctype, json, pdo_sqlite
#
#      - name: Require Laravel & Testbench
#        run: |
#          composer require --dev laravel/framework:11.x --no-update
#          composer require --dev orchestra/testbench:^9.0 --no-update
#          composer update --prefer-dist --no-interaction --no-scripts
#
#      - name: Publish Config
#        run: ./vendor/bin/testbench  vendor:publish --provider="BinaryBuilds\LaritorClient\LaritorServiceProvider" --force
#
#      - name: Run Tests
#        run: ./vendor/bin/phpunit

#  # Laravel 12 requires PHP 8.2+
#  test-laravel-12:
#    name: PHP ${{ matrix.php }} / Laravel 12.x
#    runs-on: ubuntu-latest
#    strategy:
#      matrix:
#        php: [8.2, 8.3]
#    steps:
#      - uses: actions/checkout@v4
#
#      - name: Setup PHP ${{ matrix.php }}
#        uses: shivammathur/setup-php@v2
#        with:
#          php-version: ${{ matrix.php }}
#          extensions: mbstring, bcmath, xml, ctype, json, pdo_sqlite
#
#      - name: Require Laravel & Testbench
#        run: |
#          composer require --dev laravel/framework:12.x --no-update
#          composer require --dev orchestra/testbench:^10.0 --no-update
#          composer update --prefer-dist --no-interaction --no-scripts
#
#      - name: Publish Config
#        run: ./vendor/bin/testbench  vendor:publish --provider="BinaryBuilds\LaritorClient\LaritorServiceProvider" --force
#
#      - name: Run Tests
#        run: ./vendor/bin/phpunit
